package beans;
// Generated Jun 3, 2017 2:01:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * Addition generated by hbm2java
 */
@Entity
@Table(name="addition"
    ,catalog="arkancafe"
)
public class Addition  implements java.io.Serializable {


     private Integer addId;
     private String addName;
//     private Integer unitId;
     private Long addPrice;
//      @JsonBackReference
//      @JsonIgnore
     private Set<ItemHasAddition> itemHasAdditions = new HashSet<ItemHasAddition>(0);

    public Addition() {
    }

	
    public Addition(String addName) {
        this.addName = addName;
    }
    public Addition(String addName, Integer unitId, Long price, Set<ItemHasAddition> itemHasAdditions) {
       this.addName = addName;
//       this.unitId = unitId;
       this.addPrice = price;
       this.itemHasAdditions = itemHasAdditions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="add_id", unique=true, nullable=false)
    public Integer getAddId() {
        return this.addId;
    }
    
    public void setAddId(Integer addId) {
        this.addId = addId;
    }

    
    @Column(name="add_name", nullable=false, length=50)
    public String getAddName() {
        return this.addName;
    }
    
    public void setAddName(String addName) {
        this.addName = addName;
    }

    
//    @Column(name="unit_id")
//    public Integer getUnitId() {
//        return this.unitId;
//    }
//    
//    public void setUnitId(Integer unitId) {
//        this.unitId = unitId;
//    }

    
    @Column(name="price", precision=10, scale=0)
    public Long getAddPrice() {
        return this.addPrice;
    }
    
    public void setAddPrice(Long addPrice) {
        this.addPrice = addPrice;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="addition")
//    public Set<ItemHasAddition> getItemHasAdditions() {
//        return this.itemHasAdditions;
//    }
//    
//    public void setItemHasAdditions(Set<ItemHasAddition> itemHasAdditions) {
//        this.itemHasAdditions = itemHasAdditions;
//    }




}


