package beans;
// Generated May 12, 2017 3:22:27 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Game generated by hbm2java
 */
@Entity
@Table(name = "game",
         catalog = "arkancafe"
)
public class Game implements java.io.Serializable {

    private Integer gameId;
    private Tab tab;
    private String gameName;
    private String baseUnit;
    private BigDecimal basePrice;
    private Boolean isActive;
 
    private Set<GameLine> gameLines = new HashSet<GameLine>(0);

    public Game() {
    }

    public Game(Tab tab, String gameName, String baseUnit, BigDecimal basePrice) {
        this.tab = tab;
        this.gameName = gameName;
        this.baseUnit = baseUnit;
        this.basePrice = basePrice;
    }

    public Game(Tab tab, String gameName, String baseUnit, BigDecimal basePrice, Boolean isActive, Long periode, Date startTime, Date endTime, Set<GameLine> gameLines) {
        this.tab = tab;
        this.gameName = gameName;
        this.baseUnit = baseUnit;
        this.basePrice = basePrice;
        this.isActive = isActive;
//        this.periode = periode;
//        this.startTime = startTime;
//        this.endTime = endTime;
        this.gameLines = gameLines;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "game_id", unique = true, nullable = false)
    public Integer getGameId() {
        return this.gameId;
    }

    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tab_id", nullable = false)
    public Tab getTab() {
        return this.tab;
    }

    public void setTab(Tab tab) {
        this.tab = tab;
    }

    @Column(name = "game_name", nullable = false, length = 100)
    public String getGameName() {
        return this.gameName;
    }

    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

    @Column(name = "base_unit", nullable = false, length = 25)
    public String getBaseUnit() {
        return this.baseUnit;
    }

    public void setBaseUnit(String baseUnit) {
        this.baseUnit = baseUnit;
    }

    @Column(name = "base_price", nullable = false, precision=10, scale=3)
    public BigDecimal getBasePrice() {
        return this.basePrice;
    }

    public void setBasePrice(BigDecimal basePrice) {
        this.basePrice = basePrice;
    }

    @Column(name = "isActive")
    public Boolean getIsActive() {
        return this.isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }


    @OneToMany(fetch = FetchType.LAZY, mappedBy = "game")
    public Set<GameLine> getGameLines() {
        return this.gameLines;
    }

    public void setGameLines(Set<GameLine> gameLines) {
        this.gameLines = gameLines;
    }

}
