package beans;
// Generated May 12, 2017 3:22:27 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemIngredient generated by hbm2java
 */
@Entity
@Table(name="item_ingredient"
    ,catalog="arkancafe"
)
public class ItemIngredient  implements java.io.Serializable {


     private Integer itemIngredientId;
     private Ingredient ingredient;
     private Item item;
     private Unit unit;
     private int quantity;

    public ItemIngredient() {
    }

    public ItemIngredient(Ingredient ingredient, Item item, Unit unit, int quantity) {
       this.ingredient = ingredient;
       this.item = item;
       this.unit = unit;
       this.quantity = quantity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="item_ingredient_Id", unique=true, nullable=false)
    public Integer getItemIngredientId() {
        return this.itemIngredientId;
    }
    
    public void setItemIngredientId(Integer itemIngredientId) {
        this.itemIngredientId = itemIngredientId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ing_id", nullable=false)
    public Ingredient getIngredient() {
        return this.ingredient;
    }
    
    public void setIngredient(Ingredient ingredient) {
        this.ingredient = ingredient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_id", nullable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unit_id", nullable=false)
    public Unit getUnit() {
        return this.unit;
    }
    
    public void setUnit(Unit unit) {
        this.unit = unit;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


