package beans;
// Generated May 12, 2017 3:22:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.codehaus.jackson.annotate.JsonBackReference;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name="service"
    ,catalog="arkancafe"
)
public class Service  implements java.io.Serializable {


     private Integer serviceId;
     private Tab tab;
     private String serviceName;
     @JsonBackReference
     private Set<Item> items = new HashSet<Item>(0);

    public Service() {
    }

	
    public Service(Tab tab, String serviceName) {
        this.tab = tab;
        this.serviceName = serviceName;
    }
    public Service(Tab tab, String serviceName, Set<Item> items) {
       this.tab = tab;
       this.serviceName = serviceName;
       this.items = items;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="service_id", unique=true, nullable=false)
    public Integer getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tab_id", nullable=false)
    public Tab getTab() {
        return this.tab;
    }
    
    public void setTab(Tab tab) {
        this.tab = tab;
    }

    
    @Column(name="service_name", nullable=false, length=50)
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="service")
    public Set<Item> getItems() {
        return this.items;
    }
    
    public void setItems(Set<Item> items) {
        this.items = items;
    }




}


