package beans;
// Generated May 12, 2017 3:22:27 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name="transaction"
    ,catalog="arkancafe"
)
public class Transaction  implements java.io.Serializable {


     private Integer txId;
     private Ingredient ingredient;
     private Order order;
     private long quantity;
     private Date date;

    public Transaction() {
    }

    public Transaction(Ingredient ingredient, Order order, long quantity, Date date) {
       this.ingredient = ingredient;
       this.order = order;
       this.quantity = quantity;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tx_id", unique=true, nullable=false)
    public Integer getTxId() {
        return this.txId;
    }
    
    public void setTxId(Integer txId) {
        this.txId = txId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ing_id", nullable=false)
    public Ingredient getIngredient() {
        return this.ingredient;
    }
    
    public void setIngredient(Ingredient ingredient) {
        this.ingredient = ingredient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

    
    @Column(name="quantity", nullable=false, precision=10, scale=0)
    public long getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(long quantity) {
        this.quantity = quantity;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


