package beans;
// Generated May 12, 2017 3:22:27 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TxAdjustment generated by hbm2java
 */
@Entity
@Table(name="tx_adjustment"
    ,catalog="arkancafe"
)
public class TxAdjustment  implements java.io.Serializable {


     private Integer adjustmentId;
     private Ingredient ingredient;
     private long addedQty;

    public TxAdjustment() {
    }

    public TxAdjustment(Ingredient ingredient, long addedQty) {
       this.ingredient = ingredient;
       this.addedQty = addedQty;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="adjustment_id", unique=true, nullable=false)
    public Integer getAdjustmentId() {
        return this.adjustmentId;
    }
    
    public void setAdjustmentId(Integer adjustmentId) {
        this.adjustmentId = adjustmentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ingredient_ing_id", nullable=false)
    public Ingredient getIngredient() {
        return this.ingredient;
    }
    
    public void setIngredient(Ingredient ingredient) {
        this.ingredient = ingredient;
    }

    
    @Column(name="added_qty", nullable=false, precision=10, scale=0)
    public long getAddedQty() {
        return this.addedQty;
    }
    
    public void setAddedQty(long addedQty) {
        this.addedQty = addedQty;
    }




}


