package beans;
// Generated May 12, 2017 3:22:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Unit generated by hbm2java
 */
@Entity
@Table(name="unit"
    ,catalog="arkancafe"
)
public class Unit  implements java.io.Serializable {


     private Integer unitId;
     private Unit unit;
     private String unitName;
     private int conversion;
     private Set<ItemIngredient> itemIngredients = new HashSet<ItemIngredient>(0);
     private Set<Unit> units = new HashSet<Unit>(0);
     private Set<Ingredient> ingredients = new HashSet<Ingredient>(0);

    public Unit() {
    }

	
    public Unit(Unit unit, String unitName, int conversion) {
        this.unit = unit;
        this.unitName = unitName;
        this.conversion = conversion;
    }
    public Unit(Unit unit, String unitName, int conversion, Set<ItemIngredient> itemIngredients, Set<Unit> units, Set<Ingredient> ingredients) {
       this.unit = unit;
       this.unitName = unitName;
       this.conversion = conversion;
       this.itemIngredients = itemIngredients;
       this.units = units;
       this.ingredients = ingredients;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="unit_id", unique=true, nullable=false)
    public Integer getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="base_unit_id", nullable=false)
    public Unit getUnit() {
        return this.unit;
    }
    
    public void setUnit(Unit unit) {
        this.unit = unit;
    }

    
    @Column(name="unit_name", nullable=false, length=50)
    public String getUnitName() {
        return this.unitName;
    }
    
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    
    @Column(name="conversion", nullable=false)
    public int getConversion() {
        return this.conversion;
    }
    
    public void setConversion(int conversion) {
        this.conversion = conversion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unit")
    public Set<ItemIngredient> getItemIngredients() {
        return this.itemIngredients;
    }
    
    public void setItemIngredients(Set<ItemIngredient> itemIngredients) {
        this.itemIngredients = itemIngredients;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unit")
    public Set<Unit> getUnits() {
        return this.units;
    }
    
    public void setUnits(Set<Unit> units) {
        this.units = units;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unit")
    public Set<Ingredient> getIngredients() {
        return this.ingredients;
    }
    
    public void setIngredients(Set<Ingredient> ingredients) {
        this.ingredients = ingredients;
    }




}


